-- Tạo bảng invoices
CREATE TABLE IF NOT EXISTS `invoices` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `invoice_code` varchar(255) NOT NULL,
    `booking_id` bigint unsigned NOT NULL,
    `customer_name` varchar(255) NOT NULL,
    `room_numbers` text NOT NULL,
    `check_in_date` date NOT NULL,
    `check_out_date` date NOT NULL,
    `actual_check_in` datetime DEFAULT NULL,
    `actual_check_out` datetime DEFAULT NULL,
    `room_charge` decimal(15,2) NOT NULL DEFAULT '0.00',
    `service_charge` decimal(15,2) NOT NULL DEFAULT '0.00',
    `minibar_charge` decimal(15,2) NOT NULL DEFAULT '0.00',
    `extra_charge` decimal(15,2) NOT NULL DEFAULT '0.00',
    `damage_fee` decimal(15,2) NOT NULL DEFAULT '0.00',
    `deposit_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
    `remaining_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
    `total_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
    `payment_status` varchar(255) NOT NULL DEFAULT 'unpaid',
    `issued_at` timestamp NULL DEFAULT NULL,
    `printed_at` timestamp NULL DEFAULT NULL,
    `notes` text DEFAULT NULL,
    `created_by` bigint unsigned DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `invoices_invoice_code_unique` (`invoice_code`),
    KEY `invoices_booking_id_foreign` (`booking_id`),
    KEY `invoices_created_by_foreign` (`created_by`),
    CONSTRAINT `invoices_booking_id_foreign` FOREIGN KEY (`booking_id`) REFERENCES `bookings` (`id`) ON DELETE CASCADE,
    CONSTRAINT `invoices_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;