<?php $__env->startSection('title','Chi tiết sửa phòng'); ?>
<?php $__env->startSection('content'); ?>
<?php $issue=$roomIssueRequest; ?>
<div class="admin-wrapper"><main class="admin-content">
<p class="admin-breadcrumb mb-3"><a href="<?php echo e(route('admin.dashboard')); ?>">Admin</a> / <a href="<?php echo e(route('admin.room-repairs.index')); ?>">Phòng cần sửa</a> / Chi tiết</p>
<div class="admin-page-head d-flex justify-content-between gap-3 flex-wrap"><div><h2>Sửa phòng <?php echo e($issue->currentRoom?->room_number); ?></h2><p>Yêu cầu từ booking <?php echo e($issue->booking?->booking_code); ?></p></div><a href="<?php echo e(route('admin.room-repairs.index')); ?>" class="btn btn-outline-secondary">Quay lại</a></div>
<?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?>
<?php if(session('error')): ?><div class="alert alert-danger"><?php echo e(session('error')); ?></div><?php endif; ?>
<div class="row g-3"><div class="col-lg-8"><div class="settings-section mb-3"><h5 class="fw-bold">Nội dung cần khắc phục</h5><div class="border rounded p-3 bg-light my-3"><?php echo e($issue->issue_description); ?></div><div class="d-flex flex-wrap gap-2"><?php $__currentLoopData = $issue->attachments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $attachment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="js-image-lightbox" href="<?php echo e(route('admin.room-issue-attachments.show',$attachment)); ?>" target="_blank"><img src="<?php echo e(route('admin.room-issue-attachments.show',$attachment)); ?>" style="width:160px;height:115px;object-fit:cover;border-radius:10px;border:1px solid #ddd" alt="Ảnh sự cố"></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div>
<div class="settings-section"><h5 class="fw-bold mb-3">Xác nhận hoàn tất</h5><?php if($issue->repair_status!=='completed'): ?><form method="POST" action="<?php echo e(route('admin.room-repairs.complete',$issue)); ?>" onsubmit="return confirm('Xác nhận đã khắc phục xong sự cố phòng này?')"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><textarea name="repair_note" class="form-control" rows="4" required maxlength="2000" placeholder="Ghi rõ đã sửa/thay thế gì và tình trạng sau kiểm tra..."></textarea><button class="btn btn-success w-100 mt-3">Đã sửa xong</button></form><?php else: ?><div class="alert alert-success mb-0"><strong>Đã hoàn tất <?php echo e($issue->repair_completed_at?->timezone('Asia/Ho_Chi_Minh')->format('d/m/Y H:i')); ?></strong><div><?php echo e($issue->repair_note); ?></div></div><?php endif; ?></div></div>
<div class="col-lg-4"><div class="settings-section"><h5 class="fw-bold mb-3">Thông tin xử lý</h5><div class="d-grid gap-3 small"><div><span class="text-muted d-block">Phương án của quản lý</span><strong><?php echo e(['same_category'=>'Đổi phòng cùng hạng','upgrade_category'=>'Đổi hạng phòng','no_room'=>'Giữ phòng cũ - sửa tại chỗ'][$issue->resolution_type] ?? '---'); ?></strong></div><div><span class="text-muted d-block">Phòng khách chuyển đến</span><strong><?php echo e($issue->approvedRoom?->room_number ?? 'Không có'); ?></strong></div><div><span class="text-muted d-block">Ghi chú quản lý</span><strong><?php echo e($issue->admin_note); ?></strong></div></div></div></div></div>
</main></div>
<script src="<?php echo e(asset('assets/js/image-lightbox.js')); ?>?v=<?php echo e(filemtime(public_path('assets/js/image-lightbox.js'))); ?>"></script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\Booking_Web-master\Booking_Web-master\resources\views\admin\pages\room-repairs\show.blade.php ENDPATH**/ ?>